"""Generate plain-language market commentary by feeding the latest daily
report into Claude. Saves output to reports/commentary_<date>.md and a
trimmed version into docs/index.html so it appears at the top of the
GitHub Pages dashboard.

Usage:
    python commentary.py                     # uses latest summary
    python commentary.py --report path.md    # specific report file
    python commentary.py --model X           # override default Opus 4.7

Requires ANTHROPIC_API_KEY environment variable.
"""
import argparse
import os
import re
import sys
from datetime import datetime
from pathlib import Path

import anthropic

from common import ROOT


SYSTEM_PROMPT = """你是一位專長解讀主動式 ETF 操作意圖的資深台股分析師。

接下來會收到一份「00981A 統一台股增長主動式 ETF」的每日資料報告(markdown),
內容包含基金規模、Top 20 持股權重變化、近 10 個交易日的持倉/股價/三大法人籌碼矩陣、
以及大盤對照走勢。

你的任務是寫一段給一般投資人看的「今日經理人在做什麼」白話評論。

規則:
1. 字數控制在 400-600 字。
2. 用台灣口語繁體中文,有溫度但專業,不要太僵硬。
3. 重點放在「值得注意的訊號」,例如:
   - 經理人單日大量加減碼某檔的操作(從近 10 日矩陣抓)
   - 經理人 vs 全市場法人方向背離(00981A 加碼但法人賣超,或反之)
   - 重大進出 Top 20 的個股(新進、跌出、出清)
   - 折溢價的異常變化
   - 規模快速變化造成的權重稀釋(分母效應)
4. 用具體數字佐證每個觀察(例如 "+3,200 千股"、"投信賣超 -13,938 張")。
5. 不要逐項複製表格內容,假設讀者已快速掃過報告。
6. 結尾用一句話總結 takeaway,以「一句話總結:」開頭。
7. 用 Markdown,但不要用標題(#),只用粗體與列點。
8. 不要寫免責聲明、不要說「以下為個人觀察」這種廢話開頭。

開始。"""


def latest_report_path() -> Path:
    reports_dir = ROOT / "reports"
    candidates = sorted(reports_dir.glob("*_summary.md"))
    if not candidates:
        raise FileNotFoundError(f"No *_summary.md found in {reports_dir}")
    return candidates[-1]


def generate(report_path: Path, model: str) -> tuple[str, dict]:
    report_md = report_path.read_text()
    client = anthropic.Anthropic()

    response = client.messages.create(
        model=model,
        max_tokens=4000,
        thinking={"type": "adaptive"},
        output_config={"effort": "medium"},
        system=[{"type": "text", "text": SYSTEM_PROMPT}],
        messages=[{
            "role": "user",
            "content": [{"type": "text", "text": report_md}],
        }],
    )

    text = next(b.text for b in response.content if b.type == "text")
    usage = {
        "input_tokens": response.usage.input_tokens,
        "output_tokens": response.usage.output_tokens,
        "cache_read": getattr(response.usage, "cache_read_input_tokens", 0),
        "cache_write": getattr(response.usage, "cache_creation_input_tokens", 0),
    }
    return text, usage


def inject_into_dashboard(commentary_md: str, date_str: str):
    """Prepend a commentary card to docs/index.html so it shows on Pages."""
    dashboard = ROOT / "docs" / "index.html"
    if not dashboard.exists():
        return False

    html = dashboard.read_text()
    body_md = re.sub(r"^一句話總結:", r"<br><b>一句話總結:</b>", commentary_md, flags=re.M)
    body_html = body_md
    body_html = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", body_html)
    body_html = re.sub(r"^- (.+)$", r"<li>\1</li>", body_html, flags=re.M)
    body_html = re.sub(r"((?:<li>.*</li>\s*)+)", r"<ul>\1</ul>", body_html)
    paragraphs = [
        f"<p>{p.strip()}</p>" if not p.strip().startswith("<")
        else p.strip()
        for p in body_html.split("\n\n") if p.strip()
    ]
    body_html = "\n".join(paragraphs)

    card = (
        '<div class="card" style="background:#fffaf0;border-left:4px solid #d97706;">'
        '<h2>📝 Claude 評論：今日經理人在做什麼</h2>'
        f'<div style="font-size:14px;line-height:1.7;color:#333;">{body_html}</div>'
        f'<p style="margin-top:12px;color:#999;font-size:11px;">'
        f'資料截止 {date_str} · Generated by Claude Opus 4.7</p>'
        "</div>\n"
    )

    new_html = html.replace(
        '<h1>00981A 主動統一台股增長 — 互動報告</h1>',
        '<h1>00981A 主動統一台股增長 — 互動報告</h1>\n' + card,
        1,
    )
    if new_html == html:
        # fallback: insert before first existing <div class="card">
        new_html = html.replace('<div class="card">', card + '<div class="card">', 1)

    dashboard.write_text(new_html)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", type=str, default=None)
    ap.add_argument("--model", type=str, default="claude-opus-4-7")
    args = ap.parse_args()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    report_path = Path(args.report) if args.report else latest_report_path()
    print(f"Reading: {report_path}")

    commentary, usage = generate(report_path, args.model)

    date_match = re.search(r"(\d{4}-\d{2}-\d{2})", report_path.name)
    date_str = date_match.group(1) if date_match else datetime.now().date().isoformat()

    out_path = ROOT / "reports" / f"commentary_{date_str}.md"
    header = (
        f"# 00981A — 今日經理人在做什麼({date_str})\n\n"
        f"_Claude {args.model} · "
        f"input={usage['input_tokens']} output={usage['output_tokens']} tokens · "
        f"產生於 {datetime.now().isoformat(timespec='seconds')}_\n\n---\n\n"
    )
    out_path.write_text(header + commentary + "\n")
    print(f"Wrote {out_path}")
    print(f"Tokens — input: {usage['input_tokens']}, output: {usage['output_tokens']}")

    if inject_into_dashboard(commentary, date_str):
        print(f"Injected into docs/index.html")


if __name__ == "__main__":
    main()
